### PR TITLE
Update add and edit commands for UG

### PR DESCRIPTION
**Pull request by czhiruo**

### CODE REVIEW

**Comment by czhiruo** [comment]
What does everyone think of writing `edit INDEX [CHANGE]` fo the format of edit?
Are the specifications for the optional fields in add clear enough? or can the formatting be improved?

**Comment by evanyan13** [comment]
> What does everyone think of writing `edit INDEX [CHANGE]` fo the format of edit? Are the specifications for the optional fields in add clear enough? or can the formatting be improved?

I think that works else that line will be very long. Another suggestion is edit INDEX [MODIFIER/CHANGE] 
Or mb we can have another table that list out all the fields and corresponding prefix/modifiers.

**Review by evanyan13 — COMMENTED** [review]
LGTM

**Review by evanyan13 — APPROVED** [review]
LGTM. Up to you to consider how we write the edit part

**Pull request merged**
